import LocalizedStrings from "react-localization";

export const localStrings = new LocalizedStrings({
  sp: {
    boilerPlateHeader: "Caldera RNPlaca",
    welcomeBack: "Bienvenido de nuevo",
    login: "Acceso",
    forgotPassword: "Has olvidado tu contraseña",
    placeholderEmail: "Correo electrónico",
    placeholderPassword: "Contraseña",
    changeTheme: "Cambiar de tema",
    changeLanguage: "Cambiar idioma",
    maintenanceMsg:
      "El mantenimiento programado está en curso para mejorar tu experiencia.\n¡Gracias por tu paciencia!",
    initializeCamera: "Initializing camera...",
    grantPermission: "Conceder permiso de cámara para escanear códigos QR",
    qrScanner: "Escáner QR",
    guestCheckIn: "Guest Check-in",
    loading: "Cargando...",
    anandotsav: "Anandotsav 2025",
    successiveDigital: "Successive Digital",
    ticketDetails: "Detalles del boleto",
    cameraAccessNeeded: "Camera Access Needed",
    cameraPermissionMsg:
      "This app requires access to your camera to continue. Please enable camera permissions in your device settings.",
    checkingPermission: "Checking camera permission...",
    submit: "Submit",
    kids: "Kids",
    adults: "Adults",
    checkedInGuests: "Checked-In Guests",
    totalGuests: "Total Guests",
    mobileNumber: "Mobile Number",
     checkedInKids: "Check-In Kids",
    checkedInAdults: "Check-In Adults",
  },
  en: {
    boilerPlateHeader: "RN BoilerPlate",
    welcomeBack: "Welcome Back",
    login: "Login",
    forgotPassword: "Forgot Password",
    placeholderEmail: "Email",
    placeholderPassword: "Password",
    changeTheme: "Change Theme",
    changeLanguage: "Change Language",
    serverError: "Something went wrong!",
    maintenanceMsg:
      "Scheduled maintenance is in progress to improve your experience. \nThanks for your patience!",
    initializeCamera: "Initializing camera...",
    grantPermission: "Grant camera permission to scan QR codes",
    qrScanner: "Scan your ticket QR ",
    guestCheckIn: "Guest Check-in",
    loading: "Loading...",
    anandotsav: "Anandotsav 2025",
    successiveDigital: "Successive Digital",
    ticketDetails: "Ticket Details",
    cameraAccessNeeded: "Camera Access Needed",
    cameraPermissionMsg:
      "This app requires access to your camera to continue. Please enable camera permissions in your device settings.",
    openSetting: "Open Settings",
    checkingPermission: "Checking camera permission...",
    submit: "Submit",
    kids: "Kids",
    adults: "Adults",
    checkedInGuests: "Checked-In Guests",
    totalGuests: "Total Guests",
    mobileNumber: "Mobile Number",
    checkedInKids: "Check-In Kids",
    checkedInAdults: "Check-In Adults",
  },
});

localStrings.setLanguage("en");
